export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const GET_RANDOM_TEXT_REQUEST = "GET_RANDOM_TEXT_REQUEST";
export const SAVE_HISTORY_REQUEST = "SAVE_HISTORY_REQUEST";
